// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/server.proto

package io.grpc.process;

public interface MessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:process.MessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.process.ProcessorType processorType = 1;</code>
   * @return The enum numeric value on the wire for processorType.
   */
  int getProcessorTypeValue();
  /**
   * <code>.process.ProcessorType processorType = 1;</code>
   * @return The processorType.
   */
  io.grpc.process.ProcessorType getProcessorType();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
