// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/server.proto

package io.grpc.process;

public final class ProcessServiceProtos {
  private ProcessServiceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_process_MessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_process_MessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_process_MessageReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_process_MessageReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027main/proto/server.proto\022\007process\"!\n\016Me" +
      "ssageRequest\022\017\n\007message\030\001 \001(\t\"3\n\014Message" +
      "Reply\022\022\n\nkafkaTopic\030\001 \001(\t\022\017\n\007message\030\002 \001" +
      "(\t2X\n\016ProcessService\022F\n\016ProcessMessage\022\027" +
      ".process.MessageRequest\032\025.process.Messag" +
      "eReply\"\000(\0010\001B0\n\017io.grpc.processB\024Process" +
      "ServiceProtosP\001Z\002./\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_process_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_process_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_process_MessageRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_process_MessageReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_process_MessageReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_process_MessageReply_descriptor,
        new java.lang.String[] { "KafkaTopic", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
