// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/server.proto

package io.grpc.examples.server;

public final class MessageServiceProtos {
  private MessageServiceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_MessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_MessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_MessageReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_MessageReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027main/proto/server.proto\022\006server\"\036\n\016Mes" +
      "sageRequest\022\014\n\004name\030\001 \001(\t\"3\n\014MessageRepl" +
      "y\022\022\n\nkafkaTopic\030\001 \001(\t\022\017\n\007message\030\002 \001(\t2Q" +
      "\n\016MessageService\022?\n\tSendReply\022\026.server.M" +
      "essageRequest\032\024.server.MessageReply\"\000(\0010" +
      "\001B1\n\027io.grpc.examples.serverB\024MessageSer" +
      "viceProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_server_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_server_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_MessageRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_server_MessageReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_server_MessageReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_MessageReply_descriptor,
        new java.lang.String[] { "KafkaTopic", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
