// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package io.grpc.examples.server;


public final class ServerProtoGrpc {
  private ServerProtoGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_process_MessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_process_MessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_process_MessageReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_process_MessageReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014server.proto\022\007process\"\036\n\016MessageReques" +
      "t\022\014\n\004name\030\001 \001(\t\"3\n\014MessageReply\022\022\n\nkafka" +
      "Topic\030\001 \001(\t\022\017\n\007message\030\002 \001(\t2L\n\007Process\022" +
      "A\n\tSendReply\022\027.process.MessageRequest\032\025." +
      "process.MessageReply\"\000(\0010\001B,\n\027io.grpc.ex" +
      "amples.serverB\013ServerProtoGrpcP\001Z\002./b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_process_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_process_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_process_MessageRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_process_MessageReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_process_MessageReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_process_MessageReply_descriptor,
        new java.lang.String[] { "KafkaTopic", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
